#:schema https://raw.githubusercontent.com/yunanwg/brilliant-CV/main/metadata.toml.schema.json

language = "en"

[layout]
paper_size = "a4"
awesome_color = "darknight"

before_section_skip = "1pt"
before_entry_skip = "1pt"
before_entry_description_skip = "1pt"

[layout.fonts]
regular_fonts = ["Source Sans Pro", "Source Sans 3"]
header_font = "Roboto"

[layout.header]
header_align = "left"
info_font_size = "10pt"
display_profile_photo = false

[layout.entry]
display_entry_society_first = true
display_logo = true

[inject]
inject_ai_prompt = false
inject_keywords = true
# TODO
injected_keywords_list = []

[personal]
first_name = "Stanislav"
last_name = "Stoyanov"

[personal.info]
linkedin = "grimerssy"
github = "grimerssy"
email = "grimerssy@gmail.com"

[lang.en]
header_quote = "Bachelor of Software Engineering graduate with a strong foundation in building distributed and scalable systems. Proven ability to develop high-performance applications using Rust, Go, and PostgreSQL, with hands-on experience in full-stack web development and applied cryptography. Eager to apply a passion for tackling complex engineering challenges in a professional setting."
cv_footer = "Curriculum vitae"
letter_footer = "Cover letter"

[lang.de]
header_quote = "Absolvent (B.Sc.) der Softwaretechnik mit fundierten Kenntnissen in der Entwicklung verteilter und skalierbarer Systeme. Nachgewiesene Fähigkeit, leistungsstarke Anwendungen mit Rust, Go und PostgreSQL zu erstellen, ergänzt durch praktische Erfahrung in der Full-Stack-Webentwicklung und angewandter Kryptographie. Ich bin bestrebt, meine Leidenschaft für komplexe technische Herausforderungen in einer professionellen Umgebung einzusetzen."
cv_footer = "Lebenslauf"
letter_footer = "Motivationsschreiben"
